---
title: "Contribution In and Out of the Classroom: Harvard Faculty Political Spending"
author: "Andy Wang"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}

# bringing in required libraries

knitr::opts_chunk$set(echo = FALSE)
library(stringr)
library(janitor)
library(ggplot2)
library(usmap)
library(lubridate)
library(ggthemes)
library(broom)
library(tidyverse)
library(gt)
```

```{r importdata, errors = F, warning=F}

# importing the data from the faculty, as well as reading in the correct column
# types.

faculty <- read_csv("harvard-political-spending/raw-data/faculty.csv", col_types = "ccffcc") %>%
  clean_names()

# reading in the FEC data (using a bulk search on the term "harvard", filtering
# for years from 2017 - 2020, including the correct column types)

fec <- read_csv("harvard-political-spending/raw-data/fec1720.csv",
  col_types = "ccicdccicffcccccccccccccciccccccccTddcccccccccccccccccccccccfcccccccccdcccccccc"
)

# cleaning up the faculty data: I first split the names into a full name, which
# I then split into a last name and a first name. I also did a bunch of error
# checking, since some people did in fact go by both names, or some people used
# their middle names instead of their first names. I then selected out the
# information that wasn't necessary. From there, I simplified to only use the
# first first name given, since I can do that with the FEC data too to make sure
# that no one is left out.

faculty <- faculty %>%
  mutate(
    full_name = map(
      name, ~ unlist(strsplit(., ","))
    ),
    last_name = as.character(map(
      full_name, ~ .[1]
    )),
    full_first_name = map(
      full_name, ~ .[2]
    ),
    first_split = map(
      full_first_name, ~ unlist(
        strsplit(., "\ ")
      )
    ),
    first_name = as.character(
      map(
        first_split, ~ .[2]
      )
    )
  ) %>%
  select(last_name, first_name, title, gender, race, school, department)

# used for error checking on last names to see if anyone has two last names

# mutate(last_split = map(last_name, ~ unlist(strsplit(., "\ ")))) %>%
# mutate(last2 = map(last_split, ~ .[2])) %>%
# filter(!is.na(last2))

# Now cleaning up the FEC data to put the information that we most need to the
# front, as well as adding consistent column names so that merging is easier
# later. Changed names' case from all-caps to title, so that it matches our
# Harvard dataset.

fec <- fec %>%
  mutate(
    first_split = map(
      contributor_first_name, ~ unlist(strsplit(., "\ "))
    ),
    first_name = str_to_title(map(
      first_split, ~ .[1]
    )),
    last_name = str_to_title(contributor_last_name)
  ) %>%
  select(last_name, first_name, everything())
```

```{r committeesdata, error=F, message=F}
# importing FEC committees data, cleaning up names and changing up column names
# to be consistent with other data set for easy join later.

committees <- read_delim("harvard-political-spending/raw-data/committees1920.txt",
  "|",
  escape_double = FALSE, col_names = TRUE,
  trim_ws = TRUE
) %>%
  clean_names() %>%
  mutate(committee_id = cmte_id)
```

```{r joining, error=F, message=F}
# created the master of all tables with this data, merging on first and last.
# Also using coalesce function to replace all NA amounts in contributions to 0
# (to make for accurate averages later).

faculty_fec <- left_join(faculty, fec,
  by = c("first_name", "last_name")
) %>%
  mutate(contribution_receipt_amount = coalesce(contribution_receipt_amount, 0))
```

# Faculty and their FEC Donations

This is the result after I have joined together the faculty information and the FEC donations data.

```{r displayfaculty_fec, include = T}
# using head and skim to give an overview of the data.

head(faculty_fec)
skimr::skim(faculty_fec)
```


```{r individualdonations}
# HERE

# accounting for individual donations: summarizing based on each individual.
# Creating a new column called name, based on the paste function; summarizing
# receipts, and then looking for distinct names.

individual_donations <- faculty_fec %>%
  filter(contribution_receipt_amount != 0) %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  group_by(name, title, school, department) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  ungroup() %>%
  arrange(desc(donations_sum)) %>%
  distinct(name, .keep_all = T)

mean_donation_donaters <- individual_donations %>%
  summarize(mean_donation = mean(donations_sum))
```

```{r recipients}

# first, filtering by name and transaction number to ensure that we don't double
# count people who are in two departments. Then, summarizing based on recieving
# committee name.

donation_recipients <- faculty_fec %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  distinct(name, pdf_url, .keep_all = T) %>%
  filter(contribution_receipt_amount != 0) %>%
  group_by(committee_name, committee_id) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  arrange(desc(donations_sum))


# joining with committee table

recipients_committees <- left_join(donation_recipients,
  committees,
  by = "committee_id"
) %>%
  select(-cmte_id, -cmte_nm)


# grouping by party and summarizing

parties <- recipients_committees %>%
  group_by(cmte_pty_affiliation) %>%
  summarize(total_donations = sum(donations_sum)) %>%
  filter(!is.na(cmte_pty_affiliation)) %>%
  arrange(desc(total_donations))

# summarizing by states

states <- recipients_committees %>%
  mutate(state = cmte_st) %>%
  group_by(state) %>%
  summarize(total_donations = sum(donations_sum)) %>%
  arrange(desc(total_donations))
```

```{r heatmap}

# making a heatmap using plot_usmap

plot_usmap(data = states, values = "total_donations") +
  scale_fill_continuous(
    low = "white", high = "blue",
    name = "Dollars Donated", label = scales::dollar
  ) +
  theme(legend.position = "right") +
  labs(
    title = "States Recieving Harvard Donations",
    subtitle = "Using FEC Data from 2017-2020"
  )
```

```{r overtime}

# filtering for unique name / donation id (again to discount people in two
# departments), then mutating to create a month variable. From there,
# summarizing per month

donations_over_time <- faculty_fec %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  distinct(name, pdf_url, .keep_all = T) %>%
  mutate(month = floor_date(contribution_receipt_date, "month")) %>%
  filter(!is.na(contribution_receipt_amount)) %>%
  group_by(month) %>%
  summarize(donations = sum(contribution_receipt_amount))

# plotting donations over time with ggplot

ggplot(donations_over_time, aes(x = month, y = donations)) +
  geom_line() +
  labs(
    x = "Date",
    y = "Total Donations",
    title = "Total Harvard Donations Per Month"
  ) +
  theme_classic() +
  scale_y_continuous(label = scales::dollar)
```

```{r GRSmodel}
gender_race_school_data <- faculty_fec %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  group_by(name, title, school, gender, race) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  ungroup() %>%
  arrange(desc(donations_sum)) %>%
  distinct(name, school, .keep_all = T)

mean_donation_all <- gender_race_school_data %>%
  summarize(mean_donation = mean(donations_sum))

gender_breakdown <- gender_race_school_data %>%
  group_by(gender) %>%
  summarize(mean_donation = mean(donations_sum))

race_breakdown <- gender_race_school_data %>%
  group_by(race) %>%
  summarize(mean_donation = mean(donations_sum))

school_breakdown <- gender_race_school_data %>%
  group_by(school) %>%
  summarize(mean_donation = mean(donations_sum)) %>%
  arrange(desc(mean_donation))

race_gender_breakdown <- gender_race_school_data %>%
  group_by(race, gender) %>%
  summarize(mean_donation = mean(donations_sum)) %>%
  arrange(desc(mean_donation))

ggplot(gender_race_school_data, aes(
  x = race, y = donations_sum, color = gender
)) +
  geom_jitter(width = .25, height = .1) +
  scale_y_continuous(labels = scales::dollar)

ggplot(gender_race_school_data, aes(
  x = school, y = donations_sum, color = gender
)) +
  geom_jitter(width = .25, height = .1) +
  scale_y_continuous(labels = scales::dollar)

gender_race_school_model <- lm(
  donations_sum ~ gender * race + school,
  gender_race_school_data
) %>%
  tidy(conf.int = T)
```

```{r subjects}
subject_field_data <- faculty_fec %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  filter(school %in% c("FAS", "SEAS")) %>%
  group_by(name, title, school, gender, race, department) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  ungroup() %>%
  arrange(desc(donations_sum)) %>%
  mutate(field = case_when(
    school == "SEAS" ~ "Engineering",
    department %in% c("AAAS", "ANTHRO", "ECON", "GOV", "HIST", "PSCH", "SOCSTUD", "SOCIO", "WGS") ~ "Social Sciences",
    department %in% c("ASTRO", "CHEM", "EPS", "HISTSCI", "HEBIO", "MATH", "MCBIO", "OEBIO", "PHY", "STAT", "STRBIO", "ESPP") ~ "Math/Science",
    department %in% c("CELTIC", "CLASSICS", "COMPLIT", "EALC", "ENG", "FOLKMYTH", "GERM", "HISTLIT", "HAA", "LING", "MUSIC", "NELC", "PHIL", "RELI", "ROMANCE", "SLAV", "SAS") ~ "Humanities",
    department == "ADMIN" ~ "Admin"
  ))

department_spending <- subject_field_data %>%
  distinct(name, department, .keep_all = T) %>%
  group_by(department) %>%
  summarize(mean_donation = mean(donations_sum))

ggplot(department_spending, aes(x = department, y = mean_donation)) +
  geom_col() +
  coord_flip()

ggplot(subject_field_data, aes(x = department, y = donations_sum, color = gender)) +
  geom_jitter(width = .1, height = .25) +
  coord_flip() +
  scale_y_log10(labels = scales::dollar)

subject_spending <- subject_field_data %>%
  distinct(name, field, .keep_all = T)

ggplot(subject_spending, aes(x = field, y = donations_sum, color = gender)) +
  geom_jitter(width = .1, height = .25) +
  coord_flip() +
  scale_y_log10(labels = scales::dollar)

spending_by_subject <- subject_spending %>%
  group_by(field) %>%
  summarize(mean_spending = mean(donations_sum)) %>%
  arrange(desc(mean_spending))

field_race_gender_model <- lm(
  donations_sum ~ gender * race + field,
  subject_spending
) %>%
  tidy(conf.int = T)
```

```{r diversity}
diverse_faculty <- faculty_fec %>%
  mutate(name = paste(last_name, ", ", first_name, sep = "")) %>%
  mutate(white_man = case_when(
    gender == "M" & race == "White" ~ TRUE,
    gender != "M" ~ FALSE,
    race != "White" ~ FALSE
  )) %>%
  mutate(white = case_when(
    race == "White" ~ TRUE,
    race != "White" ~ FALSE
  )) %>%
  select(white_man, everything())

# Working on University level
diversity_donations_uni <- diverse_faculty %>%
  group_by(name, title, school, white_man, white, race, gender) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  ungroup() %>%
  arrange(desc(donations_sum)) %>%
  distinct(name, school, .keep_all = T)

donations_diversity_per_school <- diversity_donations_uni %>%
  arrange(school) %>%
  group_by(school) %>%
  nest() %>%
  mutate(
    white_man = map(data, ~ sum(.$white_man)),
    white = map(data, ~ sum(.$white)),
    n = map_dbl(data, nrow),
    non_white_man_percent = 100 * (1 - (as.numeric(white_man) / n)),
    non_white_percent = 100 * (1 - (as.numeric(white) / n)),
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  ) %>%
  select(school, non_white_man_percent, non_white_percent, mean_donation, data)

ggplot(donations_diversity_per_school, aes(x = non_white_percent, y = mean_donation)) +
  geom_point() +
  geom_smooth(method = "glm", se = F)
ggplot(donations_diversity_per_school, aes(x = non_white_man_percent, y = mean_donation)) +
  geom_point() +
  geom_smooth(method = "glm", se = F)

demographics_school <- diversity_donations_uni %>%
  mutate(
    asian_man = case_when(
      race == "Asian" & gender == "M" ~ TRUE,
      race != "Asian" | gender != "M" ~ FALSE
    ),
    asian_woman = case_when(
      race == "Asian" & gender == "F" ~ TRUE,
      race != "Asian" | gender != "F" ~ FALSE
    ),
    black_woman = case_when(
      race == "African American" & gender == "F" ~ TRUE,
      race != "African American" | gender != "F" ~ FALSE
    ),
    black_man = case_when(
      race == "African American" & gender == "M" ~ TRUE,
      race != "African American" | gender != "M" ~ FALSE
    ),
    white_woman = case_when(
      race == "White" & gender == "F" ~ TRUE,
      race != "White" | gender != "F" ~ FALSE
    )
  ) %>%
  group_by(school) %>%
  nest() %>%
  mutate(
    n = map_dbl(data, nrow),
    white_man = as.numeric(map(data, ~ sum(.$white_man))) / n,
    white_woman = as.numeric(map(data, ~ sum(.$white_woman))) / n,
    asian_man = as.numeric(map(data, ~ sum(.$asian_man))) / n,
    asian_woman = as.numeric(map(data, ~ sum(.$asian_woman))) / n,
    black_man = as.numeric(map(data, ~ sum(.$black_man))) / n,
    black_woman = as.numeric(map(data, ~ sum(.$black_woman))) / n,
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  )

# Now on FAS Level
diversity_donations_fas <- diverse_faculty %>%
  filter(school %in% c("FAS", "SEAS")) %>%
  group_by(name, title, school, gender, race, department, white_man, white) %>%
  summarize(donations_sum = sum(contribution_receipt_amount)) %>%
  ungroup() %>%
  arrange(desc(donations_sum)) %>%
  mutate(field = case_when(
    school == "SEAS" ~ "Engineering",
    department %in% c("AAAS", "ANTHRO", "ECON", "GOV", "HIST", "PSCH", "SOCSTUD", "SOCIO", "WGS") ~ "Social Sciences",
    department %in% c("ASTRO", "CHEM", "EPS", "HISTSCI", "HEBIO", "MATH", "MCBIO", "OEBIO", "PHY", "STAT", "STRBIO", "ESPP") ~ "Math/Science",
    department %in% c("CELTIC", "CLASSICS", "COMPLIT", "EALC", "ENG", "FOLKMYTH", "GERM", "HISTLIT", "HAA", "LING", "MUSIC", "NELC", "PHIL", "RELI", "ROMANCE", "SLAV", "SAS") ~ "Humanities",
    department == "ADMIN" ~ "Admin"
  ))

donations_diversity_per_field <- diversity_donations_fas %>%
  distinct(name, field, .keep_all = T) %>%
  arrange(field) %>%
  group_by(field) %>%
  nest() %>%
  mutate(
    white_man = map(data, ~ sum(.$white_man)),
    white = map(data, ~ sum(.$white)),
    n = map_dbl(data, nrow),
    non_white_man_percent = 100 * (1 - (as.numeric(white_man) / n)),
    non_white_percent = 100 * (1 - (as.numeric(white) / n)),
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  ) %>%
  select(field, non_white_man_percent, non_white_percent, mean_donation, data)

demographics_fas <- diversity_donations_fas %>%
  mutate(
    asian_man = case_when(
      race == "Asian" & gender == "M" ~ TRUE,
      race != "Asian" | gender != "M" ~ FALSE
    ),
    asian_woman = case_when(
      race == "Asian" & gender == "F" ~ TRUE,
      race != "Asian" | gender != "F" ~ FALSE
    ),
    black_woman = case_when(
      race == "African American" & gender == "F" ~ TRUE,
      race != "African American" | gender != "F" ~ FALSE
    ),
    black_man = case_when(
      race == "African American" & gender == "M" ~ TRUE,
      race != "African American" | gender != "M" ~ FALSE
    ),
    white_woman = case_when(
      race == "White" & gender == "F" ~ TRUE,
      race != "White" | gender != "F" ~ FALSE
    )
  ) %>%
  group_by(field) %>%
  nest() %>%
  mutate(
    n = map_dbl(data, nrow),
    white_man = as.numeric(map(data, ~ sum(.$white_man))) / n,
    white_woman = as.numeric(map(data, ~ sum(.$white_woman))) / n,
    asian_man = as.numeric(map(data, ~ sum(.$asian_man))) / n,
    asian_woman = as.numeric(map(data, ~ sum(.$asian_woman))) / n,
    black_man = as.numeric(map(data, ~ sum(.$black_man))) / n,
    black_woman = as.numeric(map(data, ~ sum(.$black_woman))) / n,
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  )

## Now on individual subject level
donations_diversity_per_subject <- diversity_donations_fas %>%
  distinct(name, department, .keep_all = T) %>%
  arrange(department) %>%
  group_by(department) %>%
  nest() %>%
  mutate(
    white_man = map(data, ~ sum(.$white_man)),
    white = map(data, ~ sum(.$white)),
    n = map_dbl(data, nrow),
    non_white_man_percent = 100 * (1 - (as.numeric(white_man) / n)),
    non_white_percent = 100 * (1 - (as.numeric(white) / n)),
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  ) %>%
  select(department, non_white_man_percent, non_white_percent, mean_donation, data)
ggplot(donations_diversity_per_subject, aes(x = non_white_percent, y = mean_donation)) +
  geom_point() +
  geom_smooth(method = "glm", se = F)
ggplot(donations_diversity_per_subject, aes(x = non_white_man_percent, y = mean_donation)) +
  geom_point() +
  geom_smooth(method = "glm", se = F)

demographics_departments <- diversity_donations_fas %>%
  mutate(
    asian_man = case_when(
      race == "Asian" & gender == "M" ~ TRUE,
      race != "Asian" | gender != "M" ~ FALSE
    ),
    asian_woman = case_when(
      race == "Asian" & gender == "F" ~ TRUE,
      race != "Asian" | gender != "F" ~ FALSE
    ),
    black_woman = case_when(
      race == "African American" & gender == "F" ~ TRUE,
      race != "African American" | gender != "F" ~ FALSE
    ),
    black_man = case_when(
      race == "African American" & gender == "M" ~ TRUE,
      race != "African American" | gender != "M" ~ FALSE
    ),
    white_woman = case_when(
      race == "White" & gender == "F" ~ TRUE,
      race != "White" | gender != "F" ~ FALSE
    )
  ) %>%
  group_by(department) %>%
  nest() %>%
  mutate(
    n = map_dbl(data, nrow),
    white_man = as.numeric(map(data, ~ sum(.$white_man))) / n,
    white_woman = as.numeric(map(data, ~ sum(.$white_woman))) / n,
    asian_man = as.numeric(map(data, ~ sum(.$asian_man))) / n,
    asian_woman = as.numeric(map(data, ~ sum(.$asian_woman))) / n,
    black_man = as.numeric(map(data, ~ sum(.$black_man))) / n,
    black_woman = as.numeric(map(data, ~ sum(.$black_woman))) / n,
    mean_donation = as.numeric(map(data, ~ mean(.$donations_sum)))
  )
```
